---
title: "Soil_covariance"
author: "Julia Harenčár"
date: "6/27/2024"
format: 
  html:
    code-fold: true
    code-tools: true
    code-overflow: wrap
    toc: true
    number-sections: true
theme:
  light: minty
  dark: superhero
editor_options: 
  chunk_output_type: console
---

### Covariance matrices

#### Raw soil covariance

```{r}
# Correlation heatmap in ggplot world:
library(ggcorrplot)

# Import and clean soil data
# soil data
soils <- read.csv("soils_r.csv", header = T)

# sort soil data by plant ID to correspond with genetic data
soils <- soils[order(soils$plantID), ]

# remove plant 9 and Ca:Mg ratio
soils <- soils %>% 
  filter(plantID != 9) %>% 
  dplyr::select(-Ca_Mg_Ratio)

# subset raw soils data to remove genetic data:
soils_only <- soils[,5:31]

soils_cor_ggplot <- cor(soils_only)
#cor_ggplot <- cor(subset_chems_corr_above0.5)

# all variables
ggcorrplot(soils_cor_ggplot,
           lab = TRUE,              # show correlation values
           lab_size = 4,            # size of the correlation labels
           tl.cex = 11,              # axis tick label size
           tl.srt = 90)             # rotate x-axis labels

# Correlation plot matrix with psych package
library(psych)
pairs.panels(soils_only, 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE, # show correlation ellipses
             gap = 0,
             cex = 2.5    # increase correlation value label size
             )

# Correlation plot after narrowing to those with strong correlations with our main chems of inerest:
colnames(soils_only)[colnames(soils_only) == 'aluminum'] <- 'Aluminum'
subset_raw_soil <- soils_only %>% dplyr::select(Calcium,Magnesium,Nickel,Copper,Silicon,Potassium,Strontium,Boron,Aluminum,Arsenic)

# Correlation plot matrix with psych package
library(psych)
pairs.panels(subset_raw_soil, 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE, # show correlation ellipses
             gap = 0
             )
```

#### Genetic and soil distances covariance

```{r}
# Correlation heatmap in ggplot world:
library(ggcorrplot)
cor_ggplot <- cor(full_comb_no.id)
#cor_ggplot <- cor(subset_chems_corr_above0.5)

# all variables
ggcorrplot(cor_ggplot,
           lab = TRUE,              # show correlation values
           lab_size = 4,            # size of the correlation labels
           tl.cex = 11,              # axis tick label size
           tl.srt = 90)             # rotate x-axis labels
# selected variables


# Correlation plot matrix with psych package
library(psych)
pairs.panels(full_comb_no.id, 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE, # show correlation ellipses
             gap = 0,
             cex = 2.5    # increase correlation value label size
             )

# Narrow down to those with stronger correlations
subset_chems_corr_above0.5 <- full_comb_no.id %>% dplyr::select(genetic_distance,Calcium,Magnesium,Barium,Copper,Nickel,Silicon,Strontium,Zinc,Manganese,Potassium,Chromium,Cadmium,Cobalt,NH4.N,Arsenic,Selenium,Phosphorus,Sulfur,Boron,aluminum)

subset_corr_above0.5_covar_plot <- pairs.panels(subset_chems_corr_above0.5, 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE, # show correlation ellipses
             gap = 0,
             cex = 2.5 
             )

# Narrow further to those important in analysis and any that are strongly correlated with them
subset_chems_sml <- full_comb_no.id %>% dplyr::select(genetic_distance,Calcium,Magnesium,Nickel,Copper,Silicon,Strontium,Potassium,Boron,aluminum)

subset_corr_above0.5_covar_plot <- pairs.panels(subset_chems_sml, 
             method = "pearson", # correlation method
             hist.col = "#00AFBB",
             density = TRUE,  # show density plots
             ellipses = TRUE, # show correlation ellipses
             gap = 0
            # cex.labels = 1.5 # this makes the labels too big relative to the number labels... and makes genetic_distance not fit... but seems too small otherwise...
             )

```

\

\
